use error_handling::*;
#[test]
fn check(){
    assert_eq!(2+2, 4);
}
